[build]
command = "cd frontend && npm install --legacy-peer-deps && npm run build"
publish = "frontend/dist"

# Настройка перенаправления для клиентского роутинга
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200